version: '3.4'

services:
  db:
    restart: always
    image: mysql:8.0

   # command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_ROOT_PASSWORD: secret7
      MYSQL_DATABASE: test

    ports:
      - 3306:3306
