version: '3.4'

services:
  db:
    restart: always
    image: mysql:8.0
    
    environment:
      MYSQL_ROOT_PASSWORD: secret7
      MYSQL_DATABASE: test

    ports:
      - 3306:3306

  nats:
    container_name: nats
    image: nats:2.7-alpine
    ports:
      - 4222:4222